# Generated by Django 4.2.19 on 2025-02-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='dicom_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='visualization_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
