# Generated by Django 5.1.6 on 2025-02-19 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0002_dicomimage_dicom_info_dicomimage_visualization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
            ],
        ),
    ]
