# Generated by Django 5.1.6 on 2025-02-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0003_processingbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
