# Generated by Django 4.2.19 on 2025-02-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0004_alter_dicomimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
