# Generated by Django 4.2.19 on 2025-02-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0005_alter_dicomimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
