# Generated by Django 4.2.9 on 2025-02-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0006_dicomimage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomimage',
            old_name='processed_date',
            new_name='processing_completed',
        ),
        migrations.RemoveField(
            model_name='dicomimage',
            name='image_dimensions',
        ),
        migrations.RemoveField(
            model_name='dicomimage',
            name='preprocessing_steps',
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='processing_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='dicom_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
