# Generated by Django 4.2.9 on 2025-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0007_rename_processed_date_dicomimage_processing_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomimage',
            old_name='processing_completed',
            new_name='processed_date',
        ),
        migrations.RemoveField(
            model_name='dicomimage',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='dicomimage',
            name='processing_info',
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='image_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='preprocessing_steps',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='dicom_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
