# Generated by Django 4.2.9 on 2025-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0008_rename_processing_completed_dicomimage_processed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JpegImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('image_dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('preprocessing_steps', models.JSONField(default=dict)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('image_file', models.ImageField(upload_to='uploads/jpeg/')),
                ('image_type', models.CharField(choices=[('cbis-ddsm', 'CBIS-DDSM'), ('mri', 'MRI'), ('other', 'Other')], default='other', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='dicom_images',
            field=models.ManyToManyField(blank=True, to='preprocessing_app.dicomimage'),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='dicom_file',
            field=models.FileField(upload_to='uploads/dicom/'),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='visualization_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/dicom/preview/'),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='jpeg_images',
            field=models.ManyToManyField(blank=True, to='preprocessing_app.jpegimage'),
        ),
    ]
