# Generated by Django 4.2.9 on 2025-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0009_jpegimage_processingbatch_dicom_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpegimage',
            name='visualization_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/jpeg/preview/'),
        ),
    ]
