# Generated by Django 4.2.9 on 2025-06-25 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0010_jpegimage_visualization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('processed_image', models.ImageField(upload_to='processed_images/')),
                ('original_dimensions', models.CharField(max_length=50)),
                ('processed_dimensions', models.CharField(max_length=50)),
                ('psnr', models.FloatField()),
                ('mse', models.FloatField()),
                ('ssim', models.FloatField()),
                ('uqi', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
