# Generated by Django 4.2.26 on 2025-11-24 12:43

from django.db import migrations, models


def normalize_image_types(apps, schema_editor):
    JpegImage = apps.get_model('preprocessing_app', 'JpegImage')
    legacy_types = ['cbis-ddsm', 'mri']
    JpegImage.objects.filter(image_type__in=legacy_types).update(image_type='jpeg')


def reverse_normalize_image_types(apps, schema_editor):
    # Legacy project no longer differentiates between CBIS/MRI sources, so fallback to 'jpeg'
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing_app', '0011_processedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpegimage',
            name='image_type',
            field=models.CharField(choices=[('jpeg', 'JPEG Coronary Image'), ('png', 'PNG Coronary Image'), ('other', 'Other Coronary Image')], default='jpeg', max_length=20),
        ),
        migrations.RunPython(normalize_image_types, reverse_normalize_image_types),
    ]
